# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-13 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortcode',
            field=models.CharField(default='defaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
