# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180813_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
